name: flutter_chat_ui
description: >
  Actively maintained, community-driven chat UI implementation with an
  optional Firebase BaaS.
version: 1.6.10
publish_to: none
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  cached_network_image: ^3.3.0
  diffutil_dart: ^4.0.1
  equatable: ^2.0.5
  file_picker: ^10.3.7
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  meta: ">=1.8.0 <2.0.0"
  open_filex: ^4.7.0
  photo_view: ^0.15.0
  scroll_to_index: ^3.0.1
  swipe_to:
    git:
      url: https://github.com/vocotechnology/SwipeTo.git
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2

dev_dependencies:
  dart_code_metrics: ^5.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_chat_ui/assets/chat/gallery.svg
    - packages/flutter_chat_ui/assets/chat/send.svg
    - packages/flutter_chat_ui/assets/icon-arrow.png
    - packages/flutter_chat_ui/assets/icon-attachment.png
    - packages/flutter_chat_ui/assets/icon-delivered.png
    - packages/flutter_chat_ui/assets/icon-document.png
    - packages/flutter_chat_ui/assets/icon-error.png
    - packages/flutter_chat_ui/assets/icon-seen.png
    - packages/flutter_chat_ui/assets/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-arrow.png
    - packages/flutter_chat_ui/assets/2.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/2.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/2.0x/icon-document.png
    - packages/flutter_chat_ui/assets/2.0x/icon-error.png
    - packages/flutter_chat_ui/assets/2.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/2.0x/icon-send.png
    - packages/flutter_chat_ui/assets/3.0x/icon-arrow.png
    - packages/flutter_chat_ui/assets/3.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/3.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/3.0x/icon-document.png
    - packages/flutter_chat_ui/assets/3.0x/icon-error.png
    - packages/flutter_chat_ui/assets/3.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/3.0x/icon-send.png
